import type { Metadata } from "next";
import "./globals.css";
import NavLinks from "@/ui/nav-links";

export const metadata: Metadata = {
  title: "Lottery App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">      
      <body>
        <NavLinks />
        {children}
      </body>
    </html>
  );
}
